### ISSUE TITLE
Golang Argparse not picking correct value for multiple flags

### ISSUE THREAD

**Issue by ayub422** [akamensky/argparse#110]
I have a golang binary named test. I have two flags -p and -s. I want user to pass them like below scenarios:
1) ./test -p 
2) ./test -s serviceName
3) ./test -p -s serviceName

Means -p should be passed with empty value and -s should be passed with any service name. 1 and 2 are working fine but in third -p flag is taking value "-s". What i want from 3rd is -p should be empty value ("") and -s should be "serviceName"

**Comment by akamensky** [comment]
I don't see any question, but report or feature request. Please read documentation all you need to implement this is already well described there.

**Comment by AyushNarayan** [comment]
Btw congrats on getting argparse listed as golang dev package previous month
