### ISSUE TITLE
How do you get >=0 positionals?

### ISSUE THREAD

**Issue by mark-summerfield** [akamensky/argparse#113]
I want a cli like this:
```myapp -f --long option name1 name2 name3```
where -f is a flag and --long is a string arg and the names are positionals.
When I use:
```
file := parser.StringPositional(nil)
```
It accepts at most 1 file & there is no StringListPositional() function.
Also the positional is shown as an option, e.g., `[_positionalArg_clc_8 "<value>"]`

**Comment by TheDen** [comment]
AFAIK you can hide the option via adding `DISABLEDDESCRIPTIONWILLNOTSHOWUP` (referenced [here](https://pkg.go.dev/github.com/akamensky/argparse#section-readme))

Here's an example I use to hide a position in `--help`:

```
var fileName *string = parser.StringPositional(&argparse.Options{Help: "DISABLEDDESCRIPTIONWILLNOTSHOWUP"})
```

**Comment by mark-summerfield** [comment]
Thank you.
