### ISSUE TITLE
Add compatibility with complete library [ bash completions ]

### ISSUE THREAD

**Issue by nightway1** [akamensky/argparse#118]
If this library had support for bash completions it would be a detail, it would make the library much more concise.

I imagine they could do it using the complete library [https://github.com/posener/complete/tree/master](url) or using the bash completions api, it would be nice if they added it.

**Comment by akamensky** [comment]
This library is specifically for command line argument parsing. This purpose is agnostic of OS and shell environment.

Bash completion only works in bash. This would be out of scope of this library functionality.
