### ISSUE TITLE
Repository Status Question

### ISSUE THREAD

**Issue by caputchinefrobles** [akamensky/argparse#120]
Hi. Congrats for the nice work on this repository. 

I was checking the issues in order to see if there is a workaround for naming positional arguments and it seems that some of them were closed by inactivity. There are even a couple of PRs that were marked as stale. Last commit from 2 yeas ago.

My questions is: Is this repo still being maintained?

Thanks for the work.

**Comment by akamensky** [comment]
Due to personal circumstances I currently do not have time to actively work on this library. But if anyone sends a PR I am hoping to find time to review that.
