### ISSUE TITLE
Add support for repeated flags/options

### ISSUE THREAD

**Issue by akamensky** [akamensky/argparse#21]
1. Allow to repeat flags or optional arguments to specify more inputs
2. Support for multiple levels like `-vvv`

**Comment by goofinator** [comment]
It's look like some test configuration problem:
$ sonar-scanner
sonar-scanner: command not found
The command "sonar-scanner" exited with 127.

**Comment by akamensky** [comment]
@goofinator has this issue been resolved here? I have not had a chance to use this myself yet, but since you implemented this I presume you already perhaps used it somewhere?

If it is resolved, please do close this issue.

**Comment by goofinator** [comment]
I think it's finished. I can't close it (not permitted for me).
