### ISSUE TITLE
Usage(err interface{})  only uses values of type error

### ISSUE THREAD

**Issue by aefalcon** [akamensky/argparse#24]
Regarding `func (*Command) Usage(err interface{}) string`, only values of _err_ with types _subCommandError_ and _error_ are used by the function.  Because _subCommandError_ is an implementation of _error_, the argument should really be of type _error_.

It would be nice if it also accounted for _string_ and _fmt.Stringer_, but I think documentation should at least note what the supported types are.

**Comment by akamensky** [comment]
I agree it should accept strings and related types.

I may be able to look at this later.
