### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by akamensky** [akamensky/argparse#3]
Need examples to cover following topics:

- [x] Flag and Flag shorthand combining
- [x] String, Selector and List
- [x] Int and Float
- [x] File
- [x] Required vs Optional arguments
- [x] Argument validation functions
- [x] Commands simple
- [x] Commands with sub-commands and arguments
- [x] Default values example

Each example must be independent and fully functional program

**Comment by ghosthawkone** [comment]
Hey @akamensky - found this repo while looking for command line parsers to write a tool using Go. Saw that this issue has been open for a couple of years now. I'd like to get started on this.

**Comment by akamensky** [comment]
@ghosthawkone feel free to submit a PR for examples! Would appreciate it.
