### ISSUE TITLE
testFunction

### ISSUE THREAD

**Issue by goofinator** [akamensky/argparse#56]
I thought it would be nice to include a test function in the options. 
If it is defined, when creating the argument, you should test the received value of the argument with its help. If it fails, finish processing with an error. This will help the user to handle a wide range of situations when the list of values ​​is limited, not providing for all cases in the library itself.

**Comment by akamensky** [comment]
There are validation functions already, where developer can provide own validators. I.e. validate that string is URL, or a valid email address.

Is this the same? If not, what is different from what you are proposing here?

**Comment by akamensky** [comment]
See Options.Validate at https://github.com/akamensky/argparse/blob/master/argparse.go#L95

**Comment by goofinator** [comment]
Yes. I apologize - did not notice. However, it confuses me that the validator checks the original parameter string. It may make sense to validate the final value, i.e. pass interface {}.

**Comment by akamensky** [comment]
The idea behind this approach was that validators should be very reliable. And I thought originally to provide a set of pre-defined validators (i.e. checking that string is a valid email address), but did not get to implementing that.

It would possibly be okay to change argument to interface and pass already parsed value type. However at this stage it would constitute a behavior change, which is a problem.

I think there are two options to go about that:
* Leave validator as is and implement new method (call it different name), then declare validator as deprecated and eventually remove it. TBH i don't really like this approach as it is a bit convoluted
* Take a note of this and implement it correct way for v2 (which I think is inevitable as I see some bad design choices I made when created this library, and v2 could be a serious improvement for this library).

**Comment by goofinator** [comment]
Ok. So, it's better to leave this issue here as reminder?

**Comment by akamensky** [comment]
Probably good idea to have a list of items for v2. I.e. wiki page, or a text/markdown document in this repo.

**Comment by goofinator** [comment]
It can be done in the same way as in the Go repository:
https://github.com/golang/proposal/
When the critical mass of  design wishes, incompatible with  the current major version, will be established -  the v2 folder could be created. 
May be it would be better to keep all about v2 in separate branch (the v2 folder and modification of mod file) for now. 
Or some thing. Honestly,  I have no big experience of working with go modules versions of v2+.

**Comment by akamensky** [comment]
The changes for v2 sure should go to  v2 branch as intended when using go modules. 

What I meant is a place to keep a list of suggestions/proposals for v2. Either a separate ticket which would link to all other tickets. Or milestone in issues. Or a text file. Either is fine I think.

**Comment by goofinator** [comment]
ok. may be, if it'll be placed in readme for contributors.

**Comment by goofinator** [comment]
ok.
