### ISSUE TITLE
support of equals from cli

### ISSUE THREAD

**Issue by jhughes1153** [akamensky/argparse#62]
It seems like it would be useful to be able to specify --path=/home/path/to/file like you can in the python version of argparse. Currently to get around this one has to specify --path /home/path/to/file with the space and it wont parse if there is an equal sign. It took some time before I realized that I needed to have spaces instead of an equal sign before it would parse it correctly.

**Comment by akamensky** [comment]
That is great suggestion. Given I am very time constrained would appreciate a PR for this issue.

**Comment by jhughes1153** [comment]
Sure I'll start on it this weekend
