### ISSUE TITLE
Argparse variables as Global variable

### ISSUE THREAD

**Issue by iamshreeram** [akamensky/argparse#65]
1. Is there a way to set the `argparse` variables as **GLOBAL** one. Currently, the scope of argparse variables are confined only to `main()`. 
2. Is there a way to declare it in `var ( )`?

**Comment by akamensky** [comment]
It is pretty easy and has nothing to do with this library. On the other note global scope variables are evil and should only be used when absolutely necessary.

Closing as has nothing to do with this library.
