### ISSUE TITLE
Rename getter fields without Get prefix

### ISSUE THREAD

**Issue by tonimelisma** [akamensky/argparse#74]
According to [Effective Go](https://golang.org/doc/effective_go.html) getter methods should be named based on the object and shouldn't include the get prefix.

**Comment by akamensky** [comment]
I think it is a good idea to follow with standards where they make sense.

Welcome to send a PR for this if you would like to. However please keep in mind backward compatibility promise. Which means renames can only be done for internal methods.

On the other hand it would be a good idea to follow that in v2 of this library whenever that happens.

**Comment by tonimelisma** [comment]
In-line with the bot comment, here's a placeholder comment to verify this issue is in no way stale.
