### ISSUE TITLE
subparser not implemented

### ISSUE THREAD

**Issue by CITIZENDOT** [akamensky/argparse#90]
So, I am trying to follow [wyag tutorial](https://wyag.thb.lt/). I am trying this with golang. So far so good. I found all equivalent go packages. But the parser in the tutorial uses subparser. I think I can do it without it too, But I noticed it's not implemented here.

Thanks for this package.

**Comment by akamensky** [comment]
Is this a bug report? A feature request? Not clear.

This is a Golang library. It is as stated in description inspired by Pythons argoarse. But it is not a replica of that.
